import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";

import { Provider } from "react-redux";
import { store } from "@/store";
import ReduxProvider from "@/store/ReduxProvider";

export const metadata: Metadata = {
  title: "VM Modernization Pilot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col bg-white">
        <ReduxProvider>
          <Header />
          <main className="min-h-screen flex flex-col items-center justify-center bg-gray-300">
            {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
