import type { Metadata } from "next";
import "./globals.css";

import { StoreProvider } from "@/store/StoreProvider";

import AppHeader from "@/components/layout/AppHeader";
import AppSideNav from "@/components/layout/AppSideNav";

export const metadata: Metadata = {
  title: "VM Modernization Pilot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col bg-white">
        <StoreProvider>
          <div className="app-shell">
            <AppHeader />
            <div className="app-body">
              <AppSideNav />
              <main className="min-h-screen w-full flex flex-col items-center justify-center bg-gray-300">
                {children}
              </main>
            </div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
